import json
import math
import os
import subprocess
import sys
import tempfile
from pathlib import Path


FALLBACKS = {
    "red": ("#c95c54", "#e4776e"),
    "green": ("#7fa66a", "#9bc383"),
    "yellow": ("#c7a85b", "#e1c874"),
    "blue": ("#6e93c4", "#91b3df"),
    "purple": ("#9b79a8", "#b99ac4"),
    "cyan": ("#67a0a0", "#86c1be"),
}


def rgb_from_hex(color):
    color = color.removeprefix("#")
    return tuple(int(color[index:index + 2], 16) / 255 for index in (0, 2, 4))


def linear(value):
    return value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4


def oklch(color):
    red, green, blue = rgb_from_hex(color)

    red, green, blue = linear(red), linear(green), linear(blue)
    lightness = 0.4122214708 * red + 0.5363325363 * green + 0.0514459929 * blue
    green_channel = 0.2119034982 * red + 0.6806995451 * green + 0.1073969566 * blue
    blue_channel = 0.0883024619 * red + 0.2817188376 * green + 0.6299787005 * blue
    lightness = math.copysign(abs(lightness) ** (1 / 3), lightness)
    green_channel = math.copysign(abs(green_channel) ** (1 / 3), green_channel)
    blue_channel = math.copysign(abs(blue_channel) ** (1 / 3), blue_channel)

    oklab_l = 0.2104542553 * lightness + 0.7936177850 * green_channel - 0.0040720468 * blue_channel
    oklab_a = 1.9779984951 * lightness - 2.4285922050 * green_channel + 0.4505937099 * blue_channel
    oklab_b = 0.0259040371 * lightness + 0.7827717662 * green_channel - 0.8086757660 * blue_channel
    chroma = math.hypot(oklab_a, oklab_b)
    hue = (math.degrees(math.atan2(oklab_b, oklab_a)) + 360) % 360
    return oklab_l, chroma, hue


def classify(color):
    lightness, chroma, hue = oklch(color)
    if chroma < 0.05 or lightness < 0.45 or lightness > 0.85:
        return None
    if hue >= 345 or hue < 40:
        return "red"
    if hue < 75:
        return "orange"
    if hue < 110:
        return "yellow"
    if hue < 165:
        return "green"
    if hue < 220:
        return "cyan"
    if hue < 285:
        return "blue"
    if hue < 330:
        return "purple"
    return "magenta"


def lighten(color):
    values = rgb_from_hex(color)
    return "#" + "".join(f"{round(value * 255 + (255 - value * 255) * 0.28):02x}" for value in values)


def darken(color):
    values = rgb_from_hex(color)
    return "#" + "".join(f"{round(value * 255 * 0.55):02x}" for value in values)


def relative_luminance(color):
    red, green, blue = rgb_from_hex(color)
    red, green, blue = linear(red), linear(green), linear(blue)
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def contrast_ratio(first, second):
    lighter = max(relative_luminance(first), relative_luminance(second))
    darker = min(relative_luminance(first), relative_luminance(second))
    return (lighter + 0.05) / (darker + 0.05)


def best_foreground(background):
    return max(("#050506", "#e9e6df"), key=lambda color: contrast_ratio(background, color))


def ranked_colors(wallpaper):
    colors = []
    for index in range(5):
        result = subprocess.run(
            [
                "matugen",
                "image",
                "--dry-run",
                "--json",
                "hex",
                "--source-color-index",
                str(index),
                wallpaper,
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            continue
        try:
            color = json.loads(result.stdout)["colors"]["source_color"]["default"]["color"]
        except (KeyError, json.JSONDecodeError):
            continue
        if color not in colors:
            colors.append(color)
    return colors


def write_palette(wallpaper):
    candidates = ranked_colors(wallpaper)
    accent = candidates[0] if candidates else "#6e93c4"
    selected = {}

    for candidate in candidates:
        bucket = classify(candidate)
        if bucket in FALLBACKS and bucket not in selected:
            selected[bucket] = candidate

    if "red" not in selected and "orange" in selected:
        selected["red"] = selected["orange"]
    if "purple" not in selected and "magenta" in selected:
        selected["purple"] = selected["magenta"]

    colors = {}
    for name, (fallback, bright_fallback) in FALLBACKS.items():
        colors[name] = selected.get(name, fallback)
        colors[f"bright_{name}"] = lighten(colors[name]) if name in selected else bright_fallback

    lines = [
        "# Generated by ghostty-palette-generator from the current wallpaper.",
        "background = #050506",
        "foreground = #e9e6df",
        f"cursor-color = {accent}",
        f"selection-background = {darken(accent)}",
        f"selection-foreground = {best_foreground(darken(accent))}",
        "",
        "# Fixed semantic ANSI colors with compatible wallpaper hues where available.",
        "palette = 0=#111216",
        f"palette = 1={colors['red']}",
        f"palette = 2={colors['green']}",
        f"palette = 3={colors['yellow']}",
        f"palette = 4={colors['blue']}",
        f"palette = 5={colors['purple']}",
        f"palette = 6={colors['cyan']}",
        "palette = 7=#d3d0c9",
        "palette = 8=#62636a",
        f"palette = 9={colors['bright_red']}",
        f"palette = 10={colors['bright_green']}",
        f"palette = 11={colors['bright_yellow']}",
        f"palette = 12={colors['bright_blue']}",
        f"palette = 13={colors['bright_purple']}",
        f"palette = 14={colors['bright_cyan']}",
        "palette = 15=#ffffff",
        "",
    ]

    output = Path.home() / ".config/ghostty/config-colors"
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=output.parent, delete=False) as temporary:
        temporary.write("\n".join(lines))
        temporary_path = temporary.name
    os.replace(temporary_path, output)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Usage: ghostty-palette-generator IMAGE")
    image = Path(sys.argv[1])
    if not image.is_file():
        raise SystemExit(f"ghostty-palette-generator: image not found: {image}")
    write_palette(str(image))
